spring.application.name=demo

spring.datasource.url=jdbc:postgresql://ep-frosty-hill-amq7h8ky-pooler.c-5.us-east-1.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_82hCDpRULlJF
spring.datasource.hikari.connection-timeout=60000
spring.datasource.hikari.maximum-pool-size=2
spring.datasource.hikari.initialization-fail-timeout=60000

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.show-sql=true

spring.data.redis.host=rediss://default:gQAAAAAAAWZ7AAIncDFiMDBmN2MwNzU2MmI0NjY1OGU0ODFmMDY2MGRhMzNiYnAxOTE3NzE@settled-opossum-91771.upstash.io:6379
spring.data.redis.port=6379
spring.data.redis.password=Adarsh@1234A
spring.data.redis.ssl.enabled=true

app.base-url=http://localhost:8080
app.jwt-secret=your-super-secret-key-which-should-be-very-long-and-secure-12345678900
app.jwt-expiration=86400000