
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.open-in-view=false

spring.data.redis.host=rediss://default:gQAAAAAAAWZ7AAIncDFiMDBmN2MwNzU2MmI0NjY1OGU0ODFmMDY2MGRhMzNiYnAxOTE3NzE@settled-opossum-91771.upstash.io:6379
spring.data.redis.port=6379
spring.data.redis.password=gQAAAAAAAWZ7AAIncDFiMDBmN2MwNzU2MmI0NjY1OGU0ODFmMDY2MGRhMzNiYnAxOTE3NzE
spring.data.redis.ssl.enabled=true

app.base-url=https://your-railway-app.railway.app
app.jwt-secret=your-super-secret-key-which-should-be-very-long-and-secure-12345678900
app.jwt-expiration=86400000


spring.datasource.url=jdbc:postgresql://db.hrbleaowjmopyidecc.supabase.co:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=Adarsh@1234A