spring.application.name=demo

# ---------------- DATABASE ----------------
spring.datasource.url=jdbc:postgresql://${PGHOST}:${PGPORT}/${PGDATABASE}
spring.datasource.username=${PGUSER}
spring.datasource.password=${PGPASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.datasource.hikari.maximum-pool-size=5

# ---------------- REDIS ----------------
spring.data.redis.host=${REDIS_HOST}
spring.data.redis.port=${REDIS_PORT}
spring.data.redis.password=${REDIS_PASSWORD}
spring.data.redis.ssl.enabled=true

# ---------------- APP CONFIG ----------------
app.base-url=${APP_BASE_URL}
app.jwt-secret=${APP_JWT_SECRET}
app.jwt-expiration=86400000
